apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.ModuleName}}-trigger-config
  namespace: default
data:
  "cicd-trigger.yaml": |-
    apiVersion: build.knative.dev/v1alpha1
    kind: Build
    metadata:
      name: build-{{.ModuleName}}
    spec:
      serviceAccountName: build-bot
      source:
        git:
          url: https://github.com/{{.CodeRepo}}.git
          revision: master
      steps:
      - name: build-and-push
        image: "registry.cn-hangzhou.aliyuncs.com/knative-release/kaniko-project-executor:v0.6.0"
        args:
        - "--dockerfile=/workspace/Dockerfile"
        # Replace meteatamel with your actual DockerHub
        - "--destination={{.ImageRepo}}:{{.ShortCommitid}}"
        env:
        - name: DOCKER_CONFIG
          value: /builder/home/.docker
      # - name: release-service
      #   image: "registry.cn-hangzhou.aliyuncs.com/knative-sample/deployer-deployer:7620096e"
      #   args:
      #   - "--namespace=default"
      #   - "--serivce-name={{.ModuleName}}"
      #   - "--image={{.ImageRepo}}:{{.ShortCommitid}}"
