apiVersion: sources.eventing.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: {{.ModuleName}}-github-sources
spec:
  eventTypes:
  - pull_request
  ownerAndRepository: {{.CodeRepo}}
  accessToken:
    secretKeyRef:
      name: githubsecret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: githubsecret
      key: secretToken
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: {{.ModuleName}}-github-trigger

